apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-test
  template:
    metadata:
      labels:
        app: mongodb-test
    spec:
      containers:
        - name: mongodb-test
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value:
